import 'package:get/get.dart';

class Question {
  String questionText, imagepath, title, description, imageContent;
  int correctAnswer, idQuestion;
  List<String> answersList;
  bool isQuestionAnswered;
  Rx<Duration> duration;

  Question(
      this.idQuestion,
      this.questionText,
      this.imagepath,
      this.answersList,
      this.correctAnswer,
      this.isQuestionAnswered,
      this.title,
      this.imageContent,
      this.description,
      this.duration);
}

List<Question> histologyQuestions = [
  Question(
      1,
      'Paciente con una condición crónica en la que las estructuras en la región apical del epitelio no son funcionales. ¿Qué patología puede ser la causande de la falta de función de esta estructura?',
      'assets/questions_images/histology_images/pregunta_8.jpg',
      [
        'Síndrome de Kartagener',
        'Síndrome de DiGeorge',
        'Síndrome de Marfan',
        'Síndrome de Down'
      ],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_8.jpg',
      'A menudo se utiliza síndrome de Kartagener como sinónimo de Discinesia ciliar primaria, sin embargo, no son lo mismo. La discinesia ciliar primaria es una patología que afecta la función de cilios y flagelos. Mientras que el síndrome de Kartagener es la triada de Situs inversus, sinusitis crónica y bronquiectasias que son resultados de la discinesia ciliar primaria.\nEl epitelio de la imágen es un epitelio peudoestratificado ciliado, característico del revestimiento de la tráquea. Al presentarse disfunción de estos cilios (resultado de por ejemplo, una alteración en los microtúbulos que los forman), se interfiere con la capacidad del sistema respiratorio de eliminar secreciones acumuladas, resultando en sinusitis. También pueden verse afectados los flagelos de los espermatozoides (resultando en infertilidad masculina) o el transporte ciliar de los óvulos (provocando infertilidad en mujeres)',
      const Duration(seconds: 25).obs),
  Question(
      2,
      '¿En qué año se completó la secuenciación del genoma humano?',
      '',
      ['2012', '1993', '2005', '2003'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_2.jpg',
      'El proyecto del genoma humano se fundó en 1990 y duró 13 años hasta completarse la secuenciación.\n\nEl genoma humano comprende la información genética incorporada en los 46 cromosomas. Contiene una secuencia de nucleótidos de 2850 millones de pares de bases organizados en aproximadamente 23000 genes codificadores de proteinas.',
      const Duration(seconds: 12).obs),
  Question(
      3,
      '¿Paciente fumador en el que las células del epitelio pseudoestratificado ciliado de su traquea se convierte en epitelio plano. ¿Cómo se llama este proceso?',
      '',
      [
        'Hiperplasia epitelial',
        'Hipertrofia epitelial',
        'Hipotrofia epitelial',
        'Metaplasia epitelial'
      ],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_7.jpg',
      'La metaplasia epitelial es el cambio reversible de un tipo de célula epitelial madura en otro tipo de célula epitelial. Se da como una respuesta adaptativa frente al estrés, inflamación crónica u otros estímulos anómalos.\nUn ejemplo de esto es la mataplasia plana, la cual normalmente ocurre en el epitelio pseudoestratificado de traquea y bronquios en pacientes que han presentado exposición  prolongada a humo de cigarrillo.',
      const Duration(seconds: 20).obs),
  Question(
      4,
      'Las siguientes son histonas que conforman el octamero en el que se enrolla el ADN para formar el nucleosoma, excepto:',
      '',
      ['H3', 'H2A', 'H1', 'H2B'],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_4.png',
      'Las histonas son las proteinas que se encuentran presentes en la formación del nucleosoma. Las histonas H2A, H2B, H3 y H4 (2 de cada una) conforman el octamero en el que se enrolla el ADN, mientras que H1 es una pieza de cierre que va "grapando" los nucleosomas.\nEstas proteinas presentan un alto contenido de lisina y arginina (aproximadamente 20%), lo que les da una carga positiva que les permite unirse a los grupos fosfato cargados negativamente del ADN.',
      const Duration(seconds: 12).obs),
  Question(
      5,
      '¿En cuál de los siguientes no se halla epitelio plano simple?',
      '',
      ['Túbulos renales', 'Alvéolos', 'Endotelio', 'Capsula de Bowman'],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_5.png',
      'El epitelio plano simple es aquel en el que el ancho de las células es mayor que su altura y presenta solo un estrato celular de espesor. Algunas de sus ubicaciones normales son la capsula de Bowman, el endotelio, el mesotelio y los alvéolos. Sus principales funciones son de intercambio, lubricación y barrera.',
      const Duration(seconds: 12).obs),
  Question(
      6,
      '¿Cuál es una ubicación de epitelio cilindrico simple?',
      '',
      ['Cavidad bucal', 'Vesícula biliar', 'Vejiga', 'Uretra'],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_6.png',
      'El epitelio cilindrico simple aquel en el que la altura excede notablemente el ancho de la célula y presenta solo un estrato celular de espesor. Sus principales funciones son de absorción y secreción y algunas de sus ubicaciones normales son el intestino delgado, colon, vesicula biliar, estómago y glándulas gástricas.',
      const Duration(seconds: 12).obs),
  Question(
      7,
      '¿Cuál es la estructura que forma la unidad fundamental de la cromatina?',
      '',
      ['Nucleolo', 'Histona', 'ADN', 'Nucleosoma'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_3.jpg',
      'Los nucleosomas son las unidades básicas de la cromatina y representan su primer nivel de plegamiento, están compuestos por aproximadamente 146 pares de bases asociados a un complejo octámero de histonas',
      const Duration(seconds: 12).obs),
  Question(
      8,
      '¿Cuál es el elemento marcado con el número 1?',
      'assets/questions_images/histology_images/pregunta_1.jpeg',
      ['Heterocromatina', 'Eucromatina', 'Membrana nuclear', 'Poro nuclear'],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_1.jpeg',
      'En el núcleo de las células se encuentra el material genético (ADN), el cual, puede estar comprimido o no. La heterocromatina es el ADN que se encuentra condensado o comprimido y a la vista microscópica se ve densamente teñida. \n La heterocromatina se divide en 2 clases:\n\n - Constitutiva: Contiene las mismas regiones de ADN repetitivas y genéticamente inactivas consistentemente incorporadas en las mismas regiones del cromosoma cuando se compara con otras células.\n - Facultativa: Al igual que la constitutiva, se encuentra condensada y no participa en el proceso de transcripción. La diferencia, es que esta no es repetitiva, es decir, su ubicación no es igual en todos los tipos de células.\n\nPredomina en células metabólicamente inactivas, como linfocitos pequeños circulantes y espermatozoides.',
      const Duration(seconds: 12).obs),
  Question(
      9,
      'El crecimiento longitudinal de un hueso largo puede ser detenido prematuramente por una fractura a través de...',
      '',
      [
        'Cuello anatómico',
        'Disco epifisiario',
        'Linea epifisiaria',
        'Diáfisis'
      ],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_9.jpg',
      'El disco epifisiario (o cartílago de crecimiento), es la región de cartílago hialino que se encuentra entre la epífisis y la diáfisis en los huesos en crecimiento. Una fractura que afecta parcial o completamente ese cartílago se denomina "epifisiolisis", según el tipo de fractura y la manera en la que afecte a la placa epifisiaria, puede causar acortamiento de la extremidad y/o desviaciones axiales (valgo o varo)',
      const Duration(seconds: 15).obs),
  Question(
      10,
      '¿Cuál de estos nos es un glucosaminoglucano que compone la sustancia fundamental del cartílago?',
      '',
      [
        'Hialuronato',
        'Condroitín sulfato',
        'Fibras colágenas',
        'Queratán sulfato'
      ],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_10.jpg',
      'En el tejido conectivo, la matríz extracelular está compuesta por fibras proteínicas (de colágeno, elásticas y reticulares) y sustancia fundamental (proteoglucanos, glucosaminoglucanos y glucoproteinas multiadhesivas). En el caso del cartílago, lo componen 3 glucosaminoglucanos: hialuronato, condroitín sulfato y queratán sulfato. El condroitín sulfato y el queratán sulfato se unen a una proteína central para conformar el agrecán (un monómero de proteoglucanos) y, a su vez, una gran cantidad de moléculas de agrecán se asocia a una molécula lineal de hialuronato para conformar grandes aglomeraciones de proteoglucanos.',
      const Duration(seconds: 10).obs),
  Question(
      11,
      'En niños prematuros se puede presentar síndrome de dificultad respiratoria cuando los/las _________ no secretan agente tensioactivo',
      '',
      [
        'Neumocitos tipo I',
        'Células granulares pequeñas',
        'Células endoteliales',
        'Neumocitos tipo II'
      ],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_11.jpg',
      'El surfactante, secretado por los neumocitos tipo II, es el encargado de disminuir la tensión superficial alveolar y adicionalmente participa en la eliminación de material extraño. La síntesis de surfactante en el feto después de la trigésimo quinta semana de gestación y es modulado por hormonas como el cortisol, insulina, prolactina y tiroxina. Sin el surfactante, los alveolos se colapsarían en cada espiración. esto sucede en los lactantes prematuros en los cuales sus pulmones no han alcanado el desarrollo suficiente para secretar surfactante, produciéndose el síndrome de dificultad respiratoria.',
      const Duration(seconds: 13).obs),
  Question(
      12,
      '¿Qué afirmación es correcta respecto a la dermis',
      '',
      [
        'Se une a la epidermis en la capa reticular',
        'Sus células son principalmente fibroblastos',
        'Células granulares pequeñas',
        'Depende de la epidermis para los procesos metabólicos'
      ],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/histology_images/pregunta_12.jpg',
      'La dermis es una de las 3 capas que compone la piel y está compuesta por dos capas: dermis papilar superficial y dermis reticular profunda. La dermis papilar contiene principalmente colágeno, está muy vascularizada y se une a los pliegues descendentes de las crestas epidérmicas. Proporciona defensa inespecífica como barrera física, y también por medio de macrófagos, leucocitos y mastocítos',
      const Duration(seconds: 10).obs)
];

List<Question> physiologyQuestions = [
  Question(
      1,
      '¿Qué característica está presente en diabetes mellitus tipo 1 y diabetes mellitus tipo 2?',
      '',
      [
        'Daño osmótico',
        'Anticuerpos contra células del islote β',
        'Disminución de la síntesis de los receptores de insulina',
        'Cetoasidosis',
      ],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_1.jpg',
      'Tanto diabéticos tipo 1 como tipo 2 que presenten un control glucemico deficiente pueden sufrir daño osmótico. Esto se da en los tejidos que contienen aldosa reductasa (cristalino, células de Schwann, etc), ya que la aldosa reductasa convierte la glucosa en sorbitol, el cual es osmóticamente activo y se puede depositar en tejidos que no lo puedan metabolizar, por lo que tiene capacidad de atraer agua y producir daño osmótico en los tejidos, ocasionando cataratas, neuropatía periférica, entre otros.',
      const Duration(seconds: 12).obs),
  Question(
      2,
      '¿En condiciones normales, cual de los siguientes tiene concentración significativamente más alta en orina que en plasma?',
      '',
      ['Bicarbonato', 'Abúmina', 'Sodio', 'Urea'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_2.jpg',
      'Los riñones filtran un líquido que se parece al plasma en su composición. En los túbulos renales se reabsorben más del 99% del agua y aproximadamente 99% de los solutos. La proporción de urea y creatinina reabsorbidas es tan solo del 53 y el 8%, respectivamente, y por eso sus concentraciones en la orina son más altas que las plasmáticas. Normalmente se reabsorbe casi el 100% de la glucosa, que está ausente en la orina. La presencia de glucosa en la orina puede deberse a un exceso de glucosa sanguínea (como en la diabetes) o a menor absorción de la glucosa por los riñones (como en la glucosuria renal). Aunque la albúmina es una molécula relativamente pequeña (en torno a 7 nm de diámetro) tiene carga negativa y es repelida por las cargas negativas de las paredes glomerulares. Por este motivo la concentración urinaria de albúmina suele ser muy baja.',
      const Duration(seconds: 13).obs),
  Question(
      3,
      'En la policitemia, la proporción de volumen sanguíneo que ocupan os eritrocitos está aumentada, ¿cuál no es una causa de policitemia secundaria?',
      '',
      [
        'Apnea del sueño',
        'Dopaje sanguíneo',
        'Enfermedad de Caisson',
        'Insuficiencia renal'
      ],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_3.jpg',
      'La enferemedad de Caisson es una enfermedad típica de los buceadores, en la que debido a un cambio brusco de la presión se forman burbujas de N2 y He en sangre y tejidos, pero no está asociada a policitemia. Sin embargo, en las otras opciones se da un aumento de Epo (eritropoyetina), lo que provoca un aumento en la cantidad de eritrocitos.',
      const Duration(seconds: 15).obs),
  Question(
      4,
      '¿Cuál de las siguientes sobre el control de la glucosa es correcta?',
      '',
      [
        'La somatostatina liberada por las células α, inhibe la insulina',
        'El glucagón liberado por las células β, aumenta la glucosa en sangre',
        'La insulina liberada por las células β aumenta la glucosa en sangre',
        'La amilina, liberada por células β inhibe la insulina'
      ],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_4.jpg',
      'La amilina retrasa el vaciado gástrico, facilita la descomposición del glucógeno en el músculo estriado e inhibe la secreción de insulina.\nLa somatostatina si inhibe la secreción de insulina, pero es secretada por las células δ. El glucagón es liberado por las células α y, la insulina disminuye los niveles de glucosa en sangre al facilitar su captación por las células.',
      const Duration(seconds: 20).obs),
  Question(
      5,
      'Un niño de 5 años con antecedentes familiares de alergias estacionales desarrolla picor, eritema e hinchazón de la piel posterior a una inyección subcutánea de polen de pasto. ¿Cuál de los siguientes es el principal mediador químico de esta reacción cutánea?',
      '',
      ['Histamina', 'Bradicina', 'Prostaglandinas', 'Oxido nítrico'],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_5.png',
      'La histamina liberada por los mastocitos es el principal mediador de las reacciones de hipersensibilidad tipo I. La histamina causa vasodilatación de las arteriolas, lo que provoca el eritema,además contrae las células endoteliales, resultando en un aumento de la permeabilidad e hinchazón de tejido.',
      const Duration(seconds: 20).obs),
  Question(
      6,
      '¿Cuál de las siguientes es una causa de acidosis metabólica?',
      '',
      [
        'Producción reducida de H+ fijos',
        'Hiperpotasemia',
        'Aumento de la excreción renal de H+',
        'Mayor pérdida renal de bicarbonato'
      ],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_6.jpg',
      'Un aumento en la pérdida renal de bicarbonato puede causar acidosis, ya que el cuerpo no puede neutralizar el exceso de ácido.\nLas otras opciones no son causas de acidosis:\n- Un aumento de H+ fijos es causa de acidosis, no la disminución de H+ fijos\n- La acidosis provoca hiperpotasemia, al provocar que iones potasio salgan de las células para intercambiarse por hidrogeniones\n- Una reducción de la excreción renal de H+ puede ser una causa de acidosis',
      const Duration(seconds: 12).obs),
  Question(
      7,
      '¿Cuál de las siguientes opciones es correcta respecto al segundo ruido cardíaco?',
      '',
      [
        'Es más fuerte en el vertice que en la base del corazón',
        'Se produce al principio de la diástole ventricular',
        'Está dividido en la espiración',
        'No está dividido en la inspiración'
      ],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_7.jpg',
      'El segundo ruido cardíaco se produce por el cierre de las válvulas pulmonar y aórtica (por lo que se escucha mejor en la base que en el vértice). Esto sucede al inicio de la diástole. El cierre de la válvula aórtica precede al de la válvula pulmonar y durante la espiración no se diferencian ambos ruidos, pero durante la inspiración puede presentarse desdoblamiento del segundo ruido cardíaco.',
      const Duration(seconds: 15).obs),
  Question(
      8,
      '¿Cuál es un beneficio que tiene respirar por la naríz en lugar de por la boca?',
      '',
      [
        'El sistema de intercambio de calor a contracorriente promueve la pérdida de calor',
        'El aire se seca',
        'Se eliminan particulas de polvo y material extraño',
        'El aire se enfría'
      ],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_8.jpg',
      'El aire espirado, cede calor por intercambio a contracorriente para evitar la perdida excesiva de calor. El aire inspirado se calienta, humedece y pierde particulas de polvo gracias al epitelio cilíndrico ciliado que recubre la cavidad nasal',
      const Duration(seconds: 15).obs),
  Question(
      9,
      '¿Cuál de los siguientes forma parte de los ganglios basales?',
      '',
      [
        'Núcleo caudado',
        'Hipocampo',
        'Hipotálamo',
        'Núcleos olivares superiores'
      ],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_9.png',
      'Los ganglios o núcleos basales son estructuras que se encuentran en la profundidad de la sustancia blanca del encéfalo, constan de 3 pares de núcleos subcorticales:\n- Núcleo caudado\n- Putamen\n- Globo pálido\nEl núcleo subtalámico y la sustancia negra anatómicamente no forman parte de los núcleos basales, pero mantienen conexiones funcionales con estos',
      const Duration(seconds: 10).obs),
  Question(
      10,
      '¿Cuál de los siguientes es un neurotransmisor purina principal?',
      '',
      ['Colecistoquinina', 'Histamina', 'Somatostatina', 'Adenosina'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_10.jpg',
      'El ATP y la adenosina (catabolito del ATP), son transmisores purina. La colecistoquinina y la somatostatina son transmisores peptídicos y la histamina es una monoamina.',
      const Duration(seconds: 10).obs),
  Question(
      11,
      'Un hombre de 50 años presenta debilidad muscular progresiva y presenta niveles elevados de aldosterona en plasma, además presenta pH sérico en 7.6 y CO3H- en 32mEq/L. ¿Cuál es la causa más probable de la debilidad muscular en este paciente?',
      '',
      ['Hiperpotasemia', 'Hipopotasemia', 'Hipercloremia', 'Hiponatremia'],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_11.jpg',
      'La aldosterona aumenta la excreción renal de K+. La hipopotasemia hiperpolariza la membrana, esto impide que el potencial de membrana alcance el umbral y provoca debilidad muscular.',
      const Duration(seconds: 25).obs),
  Question(
      12,
      'Recién nacida presenta convulsiones y temblores 3 horas después del nacimiento. Es hija de una mujer de 24 años con diabetes mellitus gestacional mal controlada. ¿Cuál de las siguientes hormonas tiene más probabilidad de ocasionar los síntomas de la niña?',
      '',
      ['cortisol', 'Glucagón', 'Insulina', 'Hormona del crecimiento'],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/physiology_images/pregunta_12.jpg',
      'La niña presenta hipoglucemia neonatal. Debido al pobre control glucémico por parte de la madre, hay hiperglucemia e hiperinsulinismo fetal. Después del parto, la fuente de la hiperglucemia fetal se elimina, pero aún está presente el hiperinsulinismo, el cual provoca una reducción intensa en glucosa sanguinea, terminando en hipoglucemia severa. Se puede prevenir esta complicación mediante la infusión de glucosa al recién nacido posterior al nacimiento.',
      const Duration(seconds: 30).obs)
];

List<Question> biochemistryQuestions = [
  Question(
      1,
      'Una mujer de 57 años presenta fatiga, dificultad para subir escaleras y pérdida de peso. Su piel está húmeda y tiene una mirada prominente. Sus signos vitales son los siguientes:\n- FC: 112ppm\n- PA: 145/90mmHg\n- FR: 15rpm\n- SaO2: 98% al ambiente. ¿Sus laboratorios probablemente muestren elevados niveles de que hormona?',
      'assets/questions_images/biochemistry_images/pregunta_1.jpg',
      ['Adrenalina', 'Hormona tiroidea', 'Insulina', 'Cortisol'],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_1.jpg',
      'La paciente presenta signos y síntomas característicos de hipertiroidismo (exoftalmos, debilidad, taquicardia, perdida de peso), por lo que la hormona que probablemente se encuentre elevada es la hormona tiroidea.',
      const Duration(seconds: 25).obs),
  Question(
      2,
      'Un niño de 5 años es llevado al pediatra con multiples lesiones en piel. Siempre ha sido muy sensible a la luz solar. Al realizar biopsias de las lesiones que presenta en la piel, se evidenció que varias de ellas eran carcinomas escamocelulares. Ni los padres ni los hermanos del niño presentan sintomatología similar. ¿Qué enfermedad puede estar cursando el paciente?',
      'assets/questions_images/biochemistry_images/pregunta_2.jpg',
      [
        'Lupus eritematoso sistémico',
        'Esclerodermia',
        'Pioderma gangrenosa',
        'Xerodermia pigmentosa'
      ],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_2.jpg',
      'El caso es característico de xerodermia pigmentosa, una enfermedad autosómica recesiva (razón por la que ninguno de los familiares presenta un cuadro similar), en la cual el cuerpo no puede reparar el daño en el ADN ocasionado por la luz UV. Estos paciententes presentan fotosensibilidad y un riesgo hasta 10000 veces mayor de desarrollar cáncer de piel no-melanoma y 2000 veces mayor de desarrollar melanoma antes de los 20 años. Algunos pacientes también pueden presentar alteraciones neurológicas.',
      const Duration(seconds: 30).obs),
  Question(
      3,
      '¿Cuál de los siguientes valores se usa para detectar la presencia de bacterias en la orina?',
      '',
      ['Cetonas', 'Proteinas', 'Leucocitos', 'Nitritos'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_3.jpg',
      'La mayoría de organismos grammnegativos reducen nitratos a nitritos, por esto los nitritos se usan para detectar la presencia de bacterias en orina. Las cetonas están presentas en orina en diabetes. La proteinuria indica enfermedad renal y los leucocitos ertán presentes en nefropatía inflamatoria',
      const Duration(seconds: 15).obs),
  Question(
      4,
      '¿Una mujer de 54 años presenta laboratorios con LDL de 194mg/dL y HDL de 41mg/dL. Le recetan un medicamento que inhibe la producción de ácido mevalónico. ¿Cuál es un efecto secundario común de este tratamiento?',
      '',
      [
        'Lesión muscular',
        'Hepatomegalia',
        'Aborto espontaneo',
        'Crisis de ausencia'
      ],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_4.jpg',
      'Al paciente le prescribieron una estatina (Inhibidor de la 3-hidroxi-3-metilglutaril coenzima A reductasa), que evita que el HMG CoA se convierta en ácido mevalónico. Un efecto adverso común de estos medicamentos es el dolor, naño y debilidad muscular',
      const Duration(seconds: 20).obs),
  Question(
      5,
      'Un paciente de 50 años con historial de diabetes pobremente controlada desde hace 15 años, se presenta con neuropatía periférica. ¿Cuál de las siguientes enzimas contribuye al daño en este paciente?',
      '',
      ['Aldosa reductasa', 'Adenosin deaminasa', 'Hexoquinasa', 'HMG CoA'],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_5.jpg',
      'La neuropatía periférica en pacientes diabéticos mal controlados, es resultado de la conversión de glucosa en sorbitol por parte de la aldosa reductasa. El sorbitol aumenta el estrés oxidativo, especialmente en nervios periféricos y en retina, donde produce un aumento de la osmolaridad celular y una peroxidación de los lípidos de la membrana celular de los nervios periféricos que conduce a isquemia e hipoxia de los mismos',
      const Duration(seconds: 20).obs),
  Question(
      6,
      '¿Cuál de las siguientes afirmaciones es verdadera respecto al complejo piruvato deshidrogenasa (PDC)?',
      '',
      [
        'Su ausencia total es compatible con la vida',
        'Convierte el piruvato en lactato',
        'Convierte el lactato en Acetil CoA',
        'Los pacientes con deficiencia de este presentan sintomas hasta la edad adulta'
      ],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_6.jpg',
      'Gracias al complejo piruvato deshidrogenasa se da la oxidación mitocondrial del piruvato a acetil CoA para su uso en el ciclo de Krebs. En ausencia de PDC, no se puede dar este proceso, y el piruvato se convierte en lactato. La deficiencia de este complejo ocasiona sintomatología desde la infancia y, la ausencia total es incompatible con la vida.',
      const Duration(seconds: 15).obs),
  Question(
      7,
      '¿Qué característica es propiedad de la glucoquinasa?',
      '',
      [
        'Está solamente en células intestinales ',
        'Se encuentra únicamente en células del parenquima hepático y células β pancreáticas',
        'Responde a concentraciones bajas de glucemia',
        'Sirve para degradar glucógeno'
      ],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_7.png',
      'La glucoquinasa es una isoenzima de la hexoquinasa, se encuentra únicamente en células del parenquima hepático y células β pancreáticas y responde a altas concentraciones de glucemia (mayores a 5µM), lo que permite la síntesis de glucógeno.',
      const Duration(seconds: 13).obs),
  Question(
      8,
      '¿Cuál es el proceso en el cual se sintetiza glucosa a partir de glicerol, lactato y/o aminoácidos glucogénicos?',
      '',
      ['Glucogenolisis', 'Gluconeogenesis', 'Glucogenogenesis', 'Glucolisis'],
      2,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_8.jpg',
      'La gluconeogenesis consiste en la síntesis de glucosa de novo, este proceso tiene lugar principalmente en hígado y riñones y, requiere un carbono para el esqueleto de la glucosa, este carbono puede provenir de las siguientes fuentes: Lactato proveniente de glucólisis y músculo, aminoácidos glucogénicos y glicerol resultante de descomposición de triglicéridos.',
      const Duration(seconds: 10).obs),
  Question(
      9,
      '¿Cuál es el proceso mediante el cual se descompone glucógeno para obtener glucosa?',
      '',
      ['Glucogenolisis', 'Gluconeogenesis', 'Glucogenogenesis', 'Glucolisis'],
      1,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_9.png',
      'La glucogenolisis es una ruta catabólica, donde se da el proceso de degradación de glucógeno para la obtención de glucosa-6-fosfato',
      const Duration(seconds: 10).obs),
  Question(
      10,
      '¿Cuál es el proceso mediante el cual se forman reservas de glucosa en forma de glucógeno?',
      '',
      ['Glucogenolisis', 'Gluconeogenesis', 'Glucogenogenesis', 'Glucolisis'],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_10.png',
      'La glucogenogenesis es una ruta anabólica donde se sintetizan reservas de glucosa en forma de glucógeno',
      const Duration(seconds: 10).obs),
  Question(
      11,
      '¿Cuál es el proceso mediante el cual se aprovecha la glucosa para obtener energía?',
      '',
      ['Glucogenolisis', 'Gluconeogenesis', 'Glucogenogenesis', 'Glucolisis'],
      4,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_11.jpg',
      'La glucolisis es el paso inicial en el catabolismo de carbohidratos. Consiste fundamentalmente en la ruptura de moléculas de glucosa mediante oxidación para obtener energía.',
      const Duration(seconds: 10).obs),
  Question(
      12,
      '¿Qué prueba permite examinar los niveles medios de glucosa en sangre durante los últimos meses?',
      '',
      ['Hemoglobina', 'Hemoglobina S', 'Hemoglobina A1c', 'Glucosa en ayunas'],
      3,
      false,
      'Retroalimentación',
      'assets/questions_images/biochemistry_images/pregunta_12.png',
      'La mejor prueba para evaluar los niveles de glucemia en el pasado son los niveles séricos de hemoglobina glicosilada, o hemoglobina A1c, que reflejan los niveles de glucosa en sangre de los últimos 90 días y permitirán evaluar el cumplimiento terapéutico y la adecuación del tratamiento.',
      const Duration(seconds: 10).obs)
];

List<List<Question>> questions = [
  histologyQuestions,
  physiologyQuestions,
  biochemistryQuestions
];
