// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hsoSyTuPMjXj2BdFZEZ5JEWOsa0YAxc',
    appId: '1:626996554069:web:782aa24417fb926e2227dc',
    messagingSenderId: '626996554069',
    projectId: 'mediquest-b3985',
    authDomain: 'mediquest-b3985.firebaseapp.com',
    storageBucket: 'mediquest-b3985.appspot.com',
    measurementId: 'G-X76LMS0H1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuG_ZTMa0Nbg1ghNlUmLyaA9Y3-Z1BUsw',
    appId: '1:626996554069:android:b719865479c53a2c2227dc',
    messagingSenderId: '626996554069',
    projectId: 'mediquest-b3985',
    storageBucket: 'mediquest-b3985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4lIpbCGrmESjwCP5aVAiXGfiZxOu_p-k',
    appId: '1:626996554069:ios:883eb0fc350f5e262227dc',
    messagingSenderId: '626996554069',
    projectId: 'mediquest-b3985',
    storageBucket: 'mediquest-b3985.appspot.com',
    iosBundleId: 'com.keryum.mediquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4lIpbCGrmESjwCP5aVAiXGfiZxOu_p-k',
    appId: '1:626996554069:ios:de30344b349fe4c02227dc',
    messagingSenderId: '626996554069',
    projectId: 'mediquest-b3985',
    storageBucket: 'mediquest-b3985.appspot.com',
    iosBundleId: 'com.keryum.mediquest.RunnerTests',
  );
}
